name: Mlt.Api Build & Deploy

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
    paths:
      - 'mlt.api/**'
      - 'mlt.common/**'
      - 'mlt.dal/**'
      - 'mlt.services/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tag
        id: tag
        run: echo "TAG=$(if [ '${{ github.ref }}' == 'refs/heads/main' ]; then echo 'latest'; else echo 'feature'; fi)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: mlt.api.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlt.api:${{ env.TAG }}

      - name: Trigger Stack Webhook
        if: ${{ vars.MLT_API_WEBHOOK != '' }}
        run: |
          curl -X POST ${{ vars.MLT_API_WEBHOOK }} \
          -H "Content-Type: application/json" \
          -d '{"status": "success", "tag": "${{ env.TAG }}"}'