name: Mlt.Web Build & Deploy

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
    paths:
      - 'mlt.web/**'
      - '.github/workflows/mlt-web-build-and-deploy.yml'

env:
  TAG_LATEST: feature #latest
  TAG_FEATURE: feature

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine Docker tag and webhook
      id: tag
      run: |
        if [[ '${{ github.ref }}' == 'refs/heads/main' ]]; then
          echo "TAG=${{ env.TAG_LATEST }}" >> $GITHUB_ENV
          if [ -z "${{ secrets.PROD_MLT_WEB_WEBHOOK }}" ]; then
            echo "WEBHOOK=''" >> $GITHUB_ENV
            echo "Warning: PROD_MLT_WEB_WEBHOOK secret is not set."
          else
            echo "WEBHOOK=${{ secrets.PROD_MLT_WEB_WEBHOOK }}" >> $GITHUB_ENV
          fi
        else
          echo "TAG=${{ env.TAG_FEATURE }}" >> $GITHUB_ENV
          if [ -z "${{ secrets.QUALIF_MLT_WEB_WEBHOOK }}" ]; then
            echo "WEBHOOK=''" >> $GITHUB_ENV
            echo "Warning: QUALIF_MLT_WEB_WEBHOOK secret is not set."
          else
            echo "WEBHOOK=${{ secrets.QUALIF_MLT_WEB_WEBHOOK }}" >> $GITHUB_ENV
          fi
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: mlt.web.Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/mlt.web:${{ env.TAG }}

    - name: Trigger Stack Webhook
      if: ${{ env.WEBHOOK != '' }}
      run: |
        curl -X POST ${{ env.WEBHOOK }} \
        -H "Content-Type: application/json" \
        -d '{"status": "success", "tag": "${{ env.TAG }}"}'